name: Pruebas unitarias
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  release:
    types:
      - released

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
      - name: Select Java Version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # - name: Build and test UT
      #   run: mvn test -Dmaven.test.failure.ignore=true -U --no-transfer-progress
      # Aunque solo los test it que ejecutan swing requieren un display Xvfb, ejecuto todo bajo esta accion
      - name: Build and run all tests
        run: mvn verify -Dmaven.test.failure.ignore=true -U --no-transfer-progress
